name: Publish Docs

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ env.PATH }}:${{ github.workspace }}/docfx

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install docfx
        run: |
          wget https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip
          unzip docfx.zip -d docfx

      - name: Generate Documentation
        working-directory: docfx_project
        run: |
          ../docfx/docfx metadata
          ../docfx/docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx_project/_site
